// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool_webAPI.Data;

namespace SmartSchool_webAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SmartSchool_webAPI.Models.Agenda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataagenda")
                        .HasColumnType("TEXT");

                    b.Property<string>("decricao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("eventoid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("usuarioid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("eventoid");

                    b.HasIndex("usuarioid");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("SmartSchool_webAPI.Models.Evento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dataevento")
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("local")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("participantes")
                        .HasColumnType("TEXT");

                    b.Property<string>("tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("SmartSchool_webAPI.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("datanascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .HasColumnType("TEXT");

                    b.Property<string>("sexo")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            datanascimento = new DateTime(2016, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "contato@andrericardo.eti.br",
                            nome = "André",
                            senha = "123",
                            sexo = "Masculino"
                        });
                });

            modelBuilder.Entity("SmartSchool_webAPI.Models.Agenda", b =>
                {
                    b.HasOne("SmartSchool_webAPI.Models.Evento", "evento")
                        .WithMany()
                        .HasForeignKey("eventoid");

                    b.HasOne("SmartSchool_webAPI.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid");

                    b.Navigation("evento");

                    b.Navigation("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
